name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: gradcafe
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gradcafe
      PGHOST: localhost
      PGPORT: 5432
      PGDATABASE: gradcafe
      PGUSER: postgres
      PGPASSWORD: postgres
      PYTHONPATH: module_4/src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r module_4/requirements.txt

      - name: Wait for Postgres
        run: |
          python - <<'PY'
          import socket
          import time

          for _ in range(24):
              with socket.socket() as sock:
                  try:
                      sock.connect(("localhost", 5432))
                  except OSError:
                      time.sleep(5)
                  else:
                      break
          else:
              raise SystemExit("Postgres service did not become ready in time")
          PY

      - name: Run pytest suite
        working-directory: module_4
        run: python -m pytest -m "web or buttons or analysis or db or integration"
